# Generated by Django 3.2.9 on 2021-11-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_alter_todoitem_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
